Do not handle redirects multiple times
terminal42/escargot pull request #13
Opened 2020-02-27 10:57 UTC by Toflar

Fixes https://github.com/terminal42/escargot/issues/12

2020-02-27 11:16 UTC, Mynyx commented
I would prefer not to immediately follow redicrets (https://symfony.com/doc/current/components/http_client.html#redirects) and add the target of a redirect to the queue.

For example, it isn't currently checked whether the target of a redirect is prohibited by a robots.txt?

2020-02-27 11:17 UTC, Toflar commented
This would mean we need to handle redirects on our own. I don't really feel like building that but PR's welcome :)

2020-02-27 19:14 UTC, Mynyx commented
I have now tested the PR. Unfortunetly it isn't working, because ``redirect_url`` is ``null``.

2020-02-27 19:25 UTC, Mynyx commented
Maybe ``$response->getInfo('url')`` could be a solution instead. It seems to work.

>     *  - url (string) - the last effective URL of the request

https://github.com/symfony/http-client-contracts/blob/master/ResponseInterface.php#L97

2020-02-28 08:29 UTC, Toflar commented
Ah, I've misunderstood the docs then. Good find :)

2020-02-28 08:40 UTC, Mynyx requested changes

2020-02-28 08:40 UTC, Mynyx commented on src/Escargot.php
> +                    && $response->getInfo('url')
```suggestion
```

``url`` can not be ``null`` according to the ResponseInterface docs.

2020-02-28 10:37 UTC, merged